trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformVlidateJob
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          displayName: Publish Artifact
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            artifact: 'terraform-manifests-out'
            publishLocation: 'pipeline' 
        - task: TerraformInstaller@0
          displayName: Terraform Install 
          inputs:
            terraformVersion: '0.13.5'
        - task: TerraformCLI@0
          displayName: Terraform Init 
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            backendType: 'azurerm'
            backendServiceArm: 'terraform-aks-azurerm-svc-con'
            backendAzureRmResourceGroupName: 'terraform-storage-rg'
            backendAzureRmStorageAccountName: 'nehastoragebackend'
            backendAzureRmContainerName: 'tfstatfile'
            backendAzureRmKey: 'aks-base.tfstate'
            allowTelemetryCollection: false
        - task: TerraformCLI@0
          displayName: Terraform Validate
          inputs:
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
            allowTelemetryCollection: false
